project_id = "bwpnagtehvqfbneknwwt"

[functions.ai-tutor]
verify_jwt = false

[functions.get-document-url]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.bank-webhook]
verify_jwt = false